services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: eletronica
      MONGO_INITDB_ROOT_PASSWORD: eletronica
    volumes:
      - ./container:/data/     

  mongo-express:

    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: eletronica
      ME_CONFIG_MONGODB_ADMINPASSWORD: eletronica
      ME_CONFIG_MONGODB_URL: mongodb://eletronica:eletronica@mongo:27017/
       